# This is a basic workflow to help you get started with Actions
 
name:
  First BTP Related Job
  # Controls when the workflow will run
on:
  # Triggers the workflow every 1 minutes
  schedule:
    - cron: "*/5 * * * *"
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
