name: Get Package Names CPI

on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"

jobs:
  oauth-and-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get OAuth Token
        id: oauth
        run: |
          OAUTH_TOKEN_URL='https://haleon-cpi-dev-7ua1w2tv.authentication.eu20.hana.ondemand.com/oauth/token?grant_type=client_credentials';
          OAUTH_RESPONSE=$(curl -s -X GET "$OAUTH_TOKEN_URL" -H 'Authorization: Basic c2ItZTMyNzJjNWQtZGVkNy00Yjk3LTk4ZjUtYjJlOTM4M2Q1ZTk4IWI3MjU3fGl0IWIyNTk6ODEwYjc3MDQtZjExNi00MDQzLWJjODctODlhOTYxNDk4NGI2JFJPLUtmOUQ3a2hqclAwMTR4Z1RYQndwYUx5TDlkU2Jmb1V6NUVUZEdtUEE9')
          OAUTH_TOKEN=$(echo "$OAUTH_RESPONSE" | jq -r '.access_token')
          echo "::set-output name=token::$OAUTH_TOKEN"
         
      - name: Use OAuth Token for API Call
        run: |
          TOKEN="${{ steps.oauth.outputs.token }}"
          API_URL="https://haleon-cpi-dev-7ua1w2tv.authentication.eu20.hana.ondemand.com/api/v1/IntegrationPackages"

        - name: Install dependencies
      run: 
          npm install
          npm install axios
          node - <<EOF
          const axios = require('axios');

          async function makeApiCall() {
            try {
              const response = await axios.get(API_URL, {
                headers: {
                  Authorization: `Bearer ${TOKEN}`
                }
              });
              console.log('API Response:', response.data);
            } catch (error) {
              console.error('API Error:', error);
            }
          }

          makeApiCall();
          EOF
