name: Get Package Names CPI

on: 
  # Triggers the workflow every 5 minutes
    schedule:
    - cron: "*/5 * * * *"

jobs:
  oauth-and-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get OAuth Token
        id: oauth
        run: |
          OAUTH_TOKEN_URL='ffffff';
          OAUTH_RESPONSE=$(curl -s -X GET "$OAUTH_TOKEN_URL" -H 'Authorization: Basic fewe'
          OAUTH_TOKEN=$(echo "$OAUTH_RESPONSE" | jq -r '.access_token')
          echo "token=$OAUTH_TOKEN" >> $GITHUB_OUTPUT
          
      - name: Use OAuth Token for API Call
        run: |
          TOKEN="${{ steps.oauth.outputs.token }}"
          API_URL="ddddd"

          npm install axios
          node - <<EOF
          const axios = require('axios');

          async function makeApiCall() {
            try {
              const response = await axios.get(${API_URL}, {
                headers: {
                  Authorization: "Bearer ${TOKEN}"
                  Accept: "application/json"
                }
              });

              console.log('API Response:', response.data);
            } catch (error) {
              console.error('API Error:', error);
            }
          }

          makeApiCall();
          EOF
